query CommunityPools(
    $day: Int
    $month: Int
    $orderBy: Pool_orderBy
    $orderDirection: OrderDirection
    $first: Int
    $skip: Int
  ) {
    kassandras {
      pool_count
    }
    pools(
      where: {
         featured: false
      }
      orderBy: $orderBy
      orderDirection: $orderDirection
      first: $first
      skip: $skip
    ) {
      id
      name
      symbol
      logo
      address
      unique_investors
      chain_id
      chain {
        logo: icon
      }
      price_usd
      total_value_locked_usd
      is_private_pool
      volumes(
        where: { period: 86400 }
        orderBy: timestamp
        orderDirection: desc
        first: 1
      ) {
        volume_usd
      }
      now: price_candles(
        where: { base: "usd", period: 3600 }
        orderBy: timestamp
        orderDirection: desc
        first: 1
      ) {
        timestamp
        close
      }
      day: price_candles(
        where: { base: "usd", period: 3600, timestamp_gt: $day }
      ) {
        timestamp
        close
      }
      month: price_candles(
        where: { base: "usd", period: 3600, timestamp_gt: $month }
        orderBy: timestamp
        first: 1
      ) {
        timestamp
        close
      }
      underlying_assets {
        token {
          logo
          wraps {
            logo
          }
        }
      }
    }
  }