query CommunityPools(
    $orderBy: Pool_orderBy
    $orderDirection: OrderDirection
    $first: Int
    $skip: Int
    $chainInId: [ID!]
    $chainInString: [String!]
  ) {
    chains (
      where: {
        id_in: $chainInId
      }
    ) {
      pool_count
    }
    pools(
      where: {
         chain_in: $chainInString
      }
      orderBy: $orderBy
      orderDirection: $orderDirection
      first: $first
      skip: $skip
    ) {
      id
      name
      symbol
      logo
      address
      unique_investors
      fee_join_broker
      chain_id
      pool_id
      chain {
        logo: icon
      }
      change
      price_usd
      total_value_locked_usd
      is_private_pool
      volumes(
        where: { period: 86400 }
        orderBy: timestamp
        orderDirection: desc
        first: 1
      ) {
        volume_usd
      }
      underlying_assets {
        token {
          logo
          wraps {
            logo
          }
        }
      }
    }
  }