query Delegations($id: String) {
  delegations(where: { from: $id, votingPower_gt: 0 }) {
    pool
    votingPower
    to {
      id
    }
    from {
      id
    }
  }

  received: delegations(where: { to: $id, from_not: $id }) {
    pool
    votingPower
    from {
      id
    }
    to {
      id
    }
  }
}
