query ManagerPoolInfo($manager: String, $id: ID) {
      pools(where: { manager: $manager, id: $id }) {
        id
        address
        vault
        chain_id
        logo
        pool_version
        is_private_pool
        decimals
        chain {
          id
          logo: icon
          name
          token_name
          token_symbol
          token_decimals
          rpc_urls
          block_explorer_url
          seconds_per_block
          address_wrapped
        }
        name
        symbol
        pool_id
        total_value_locked_usd
        underlying_assets_addresses
        controller
        price_usd
      }
    }