query PoolCharts($id: ID!, $price_period: Int!, $period_selected: Int!) {
    pool(id: $id) {
      price_usd # pool asset price
      # price candlestick
      # just taking the close value can make a line graph
      # base can be usd or btc
      # period is in seconds, 5m, 15m, 1h, 4h, 1d, 7d
      # timestamp_gt it's since when to catch
      price_candles(
        where: {
          base: "usd"
          period: $price_period
          timestamp_gt: $period_selected
        }
        orderBy: timestamp
        first: 365
      ) {
        timestamp
        close
      }
      # hourly TVL chart
      total_value_locked(
        where: { base: "usd", timestamp_gt: $period_selected }
        orderBy: timestamp
        first: 365
      ) {
        close
        timestamp
      }
      # hourly allocation chart
      weight_goal_last: weight_goals(
        orderBy: start_timestamp
        orderDirection: desc
        first: 1
      ) {
        start_timestamp
        end_timestamp
        weights {
          asset {
            token {
              id
              symbol
            }
          }
          weight_normalized
        }
      }
      weight_goals(
        where: { start_timestamp_gt: $period_selected }
        orderBy: start_timestamp
        orderDirection: desc
        first: 1000
      ) {
        start_timestamp
        end_timestamp
        weights {
          asset {
            token {
              id
              symbol
            }
          }
          weight_normalized
        }
      }
    }
  }