query PoolData($id: ID!) {
  pool(id: $id) {
    id
    address
    price_usd
    decimals
    total_value_locked_usd
    vault
    vault_id
    controller
    chain_id
    logo
    pool_version
    strategy
    is_private_pool
    supply
    fee_join_broker
    manager {
      id
      nickname
      image
    }
    chain {
      id
      logo: icon
      name
      token_name
      token_symbol
      token_decimals
      rpc_urls
      block_explorer_url
      seconds_per_block
      address_wrapped
    }
    name
    founded_by
    symbol
    pool_id
    url
    summary
    short_summary
    # partners {
    #   logo
    #   url
    # }
    underlying_assets_addresses
    underlying_assets(orderBy: weight_normalized, orderDirection: desc) {
      balance
      weight_normalized
      weight_goal_normalized
      token {
        id
        name
        logo
        symbol
        decimals
        is_wrap_token
        wraps {
          id
          decimals
          symbol
          name
          logo
        }
      }
    }
    weight_goals(orderBy: end_timestamp, orderDirection: desc, first: 2) {
      start_timestamp
      end_timestamp
      weights(orderBy: weight_normalized, orderDirection: desc) {
        asset {
          token {
            id
          }
        }
        weight_normalized
      }
    }
  }
}
