query PoolAssets($id: ID!) {
      pool(id: $id) {
        pool_version
        underlying_assets(orderBy: weight_normalized, orderDirection: desc) {
          balance
          weight_normalized
          weight_goal_normalized
          token {
            id
            name
            logo
            symbol
            decimals
            is_wrap_token
            wraps {
              id
              decimals
              symbol
              name
              logo
            }
          }
        }
        weight_goals(orderBy: end_timestamp, orderDirection: desc, first: 2) {
          start_timestamp
          end_timestamp
          weights(orderBy: weight_normalized, orderDirection: desc) {
            asset {
              token {
                id
                name
                symbol
                decimals
              }
            }
            weight_normalized
          }
        }
      }
}