query PoolJoins($id: ID!, $timestamp: Int!) {
    pool(id: $id) {
      volumes(first: 1000, where: { period: 86400, swap_pair_in: ["broker", "manager"], type: "join", timestamp_gt: $timestamp }) {
        volume_usd,
      }
    }
  }