query StrategyPool($strategy: String) {
    pools(where: { strategy: $strategy, manager_not: $strategy }) {
        id
        name
        logo
        chain {
            logo: icon
        }
    }
}
