query TokensInfo($whitelist: [ID!]!, $id: ID!) {
    tokens(where: { id_in: $whitelist }) {
      id
      name
      logo
      symbol
      decimals
    }
    pool(id: $id) {
      underlying_assets_addresses
    }
}