mutation SavePool(
    $controller: String!
    $chainId: Int!
    $signature: String!
    $logo: String
    $shortSummary: String
    $summary: String
  ) {
    savePool(
      controller: $controller
      chainId: $chainId
      signature: $signature
      logo: $logo
      shortSummary: $shortSummary
      summary: $summary
    ) {
      message
      ok
    }
}